version: "3.7"
networks:
  whd:
volumes:
  whd_db:
services:
  db:
    container_name: postgres-whd
    image: postgres:10-alpine
    environment: 
      POSTGRES_PASSWORD: "postgres"
    ports:
    - "5432:5432"
    volumes:
      - whd_db:/var/lib/postgres/
    networks:
      - whd
  whd:
    container_name: whdinstance
    environment:
      EMBEDDED: 'false'
      DB_HOST: "172.16.100.155"
      PGPASSWORD: "postgres"
    build:
      context: .
      args:
        EMBEDDED: 'false'
    image: lakeshore/whd:12.7.8
    ports:
    - "8081:8081"
    networks:
      - whd