version: "3.7"
networks:
  whd:
volumes:
  whd_db:
services:
  db:
    container_name: postgres-whd
    image: postgres:10-alpine
    environment: 
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
    - "5432:5432"
    volumes:
      - whd_db:/var/lib/postgres/
    networks:
      - whd
  whd:
    container_name: webhelpdesk
    restart: unless-stopped
    environment:
      EMBEDDED: 'false'
      DB_HOST: $DB_HOST
      PGPASSWORD: $PGPASSWORDD
    build:
      context: .
      args:
        EMBEDDED: 'false'
    image: https://ghcr.io/lakeshoresavings/webhelpdesk:12.7.8
    ports:
    - "8081:8081"
    networks:
      - whd
