name: Docker Image CI

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    
    - name: Get Version
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & Push Docker Images
      with:
        image: webhelpdesk
        tags: ${{ env.VERSION }},latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
