
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    
    - name: Get Version
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
      
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & Push Docker Images
      with:
        image: lakeshoresavings/webhelpdesk
        tags: ${{ env.VERSION }},latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
